/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package aofDot.DotParser;

public interface ParserConstants {

  int EOF = 0;
  int EDGE_DIRECTED = 9;
  int EDGE_UNDIRECTED = 10;
  int SEMI = 11;
  int DOUBLE = 12;
  int COMMA = 13;
  int EQUAL = 14;
  int SPACE = 15;
  int LBRACKET = 16;
  int RBRACKET = 17;
  int LBRACE = 18;
  int RBRACE = 19;
  int LB = 20;
  int SUBGRAPH = 21;
  int NODE = 22;
  int EDGE = 23;
  int DIGRAPH = 24;
  int GRAPH = 25;
  int STRICT = 26;
  int STRING = 27;
  int ID = 28;
  int NUMBER = 29;

  int DEFAULT = 0;
  int IN_COMMENT = 1;
  int IN_COMMENT_OL = 2;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"/*\"",
    "<token of kind 3>",
    "\"*/\"",
    "\"//\"",
    "<token of kind 6>",
    "\"\\n\"",
    "\"\\r\"",
    "\"->\"",
    "\"--\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\" \"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<LB>",
    "\"subgraph\"",
    "\"node\"",
    "\"edge\"",
    "\"digraph\"",
    "\"graph\"",
    "\"strict\"",
    "<STRING>",
    "<ID>",
    "<NUMBER>",
  };

}
